resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: tahsin/git-pull-resource
    tag: 1.0.0

- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource

resources:
- name: pull-request
  type: pull-request
  source:
    owner: tahsinrahman
    repo: test-status
    access_token: ((access_token))
    label: ok-to-test
    org: appscode
- name: notify
  type: slack-notification
  source:
    url: ((slack-webhook))

jobs:
- name: test-pr
  plan:
  - get: pull-request
    trigger: true
    version: every
  - put: pull-request
    params:
      path: pull-request
      status: pending
  - task: test-pr
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ubuntu
      inputs:
      - name: pull-request
      run:
        path: pull-request/git-pull/test.sh
        args: []
    on_success:
      do:
      - put: pull-request
        params:
          path: pull-request
          status: success
      - put: notify
        params:
          username: ghost
          text: test-succeed
    on_failure:
      do:
      - put: pull-request
        params:
          path: pull-request
          status: failure
      - put: notify
        params:
          username: ghost
          text: test-failed
